title: <center>Md Azmat Raza</center># your name (or website title) here
logo: "/azmat2.png ?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br><br>
  <a href="mailto:mdazmatraza53@gmail.com">mdazmatraza53@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/md-azmat-raza/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/AZMATRAZA/">Gihub</a> 
theme: jekyll-theme-minimal
